name: convert_json
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0


dev_dependencies:
  pedantic: ^1.9.0
  json_serializable: ^3.4.1
  build_runner: ^1.10.0
